apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-initializer
        image: mysql:8.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Running database initialization script..."
            sh /docker-entrypoint-initdb.d/db-setup.sh
        env:
        - name: MYSQL_HOST
          value: "database-service"
        volumeMounts:
        - name: initdb-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: initdb-scripts
        configMap:
          name: db-init-script
