# Use a minimal Nginx image
FROM nginx:alpine

# Copy the custom Nginx configuration to overwrite the default one
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the static HTML, CSS, and JS files to the Nginx public directory
COPY index.html index.js style.css /usr/share/nginx/html/

# Nginx runs on port 80
EXPOSE 80

# The default Nginx CMD will start the server