apiVersion: apps/v1
kind: Deployment # 1. Frontend Deployment
metadata:
  name: frontend-deployment
  labels:
    app: expense-tracker
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
      tier: frontend
  template:
    metadata:
      labels:
        app: expense-tracker
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: expense-tracker-frontend:v1 # Your custom image
        imagePullPolicy: Never # Tell Kubernetes not to pull from external registry
        ports:
        - containerPort: 80 # Nginx runs on port 80
        # No ENV vars needed, as Nginx is configured in nginx.conf

---
apiVersion: v1
kind: Service # 2. Frontend Service (External Access)
metadata:
  name: frontend-service
  labels:
    app: expense-tracker
    tier: frontend
spec:
  type: NodePort # Allows external access via Minikube's IP
  selector:
    app: expense-tracker
    tier: frontend
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80 # Container port
    nodePort: 30080 # Optional: Specify a well-known port (30000-32767)